# Based on ISO 3166-1

INDX_COUNTRY_NAME_EN = 0
INDX_COUNTRY_NAME_NA = 1
INDX_COUNTRY_CODE2 = 2
INDX_COUNTRY_CODE3 = 3

country_code =[
    ['GHANA', 'Ghana', 'GH', 'GHA'],
    ['GABON', 'Gabon', 'GA', 'GAB'],
    ['GUYANA', 'Guyana', 'GY', 'GUY'],
    ['GAMBIA', 'Gambia', 'GM', 'GMB'],
    ['GUERNSEY', 'Guernsey', 'GG', 'GGY'],
    ['GUADELOUPE', 'Guadeloupe', 'GP', 'GLP'],
    ['GUATEMALA', 'Guatemala', 'GT', 'GTM'],
    ['GUAM', 'Guam', 'GU', 'GUM'],
    ['GRENADA', 'Grenada', 'GD', 'GRD'],
    ['GREECE', 'Ελλάς', 'GR', 'GRC'],
    ['GREENLAND', 'Greenland', 'GL', 'GRL'],
    ['GUINEA', 'Guinée', 'GN', 'GIN'],
    ['GUINEA-BISSAU', 'Guiné-Bissau', 'GW', 'GNB'],
    ['NAMIBIA', 'Namibia', 'NA', 'NAM'],
    ['NAURU', 'Naoero', 'NR', 'NRU'],
    ['NIGERIA', 'Nigeria', 'NG', 'NGA'],
    ['ANTARCTICA', 'Antarctica', 'AQ', 'ATA'],
    ['REPUBLIC OF SOUTH SUDAN', 'South Sudan', 'SS', 'SSD'],
    ['SOUTH AFRICA', 'South Africa', 'ZA', 'ZAF'],
    ['NETHERLANDS', 'Nederland', 'NL', 'NLD'],
    ['NETHERLANDS ANTILLES', 'Netherlands Antilles', 'AN', 'ANT'],
    ['NEPAL', 'नेपाल', 'NP', 'NPL'],
    ['NORWAY', 'Norge', 'NO', 'NOR'],
    ['NORFOLK ISLAND', 'Norfolk Island', 'NF', 'NFK'],
    ['NEW CALEDONIA', 'New Caledonia', 'NC', 'NCL'],
    ['NEW ZEALAND', 'New Zealand', 'NZ', 'NZL'],
    ['NIUE', 'Niue', 'NU', 'NIU'],
    ['NIGER', 'Niger', 'NE', 'NER'],
    ['NICARAGUA', 'Nicaragua', 'NI', 'NIC'],
    ['KOREA', '대한민국', 'KR', 'KOR'],
    ['DENMARK', 'Danmark', 'DK', 'DNK'],
    ['DOMINICAN REPUBLIC', 'Dominican Republic', 'DO', 'DOM'],
    ['DOMINICA', 'Dominica', 'DM', 'DMA'],
    ['GERMANY', 'Deutschland', 'DE', 'DEU'],
    ['EAST TIMOR', 'Timor-Leste', 'TL', 'TLS'],
    ["LAO PEOPLE'S DEMOCRATIC REPUBLIC", 'ນລາວ', 'LA', 'LAO'],
    ['LIBERIA', 'Liberia', 'LR', 'LBR'],
    ['LATVIA', 'Latvija', 'LV', 'LVA'],
    ['RUSSIAN FEDERATION', 'Россия', 'RU', 'RUS'],
    ['LEBANON', 'لبنان', 'LB', 'LBN'],
    ['LESOTHO', 'Lesotho', 'LS', 'LSO'],
    ['REUNION', 'Reunion', 'RE', 'REU'],
    ['ROMANIA', 'România', 'RO', 'ROU'],
    ['LUXEMBOURG', 'Lëtzebuerg', 'LU', 'LUX'],
    ['RWANDA', 'Rwanda', 'RW', 'RWA'],
    ['LIBYAN ARAB JAMAHIRIYA', 'ليبيا', 'LY', 'LBY'],
    ['LITHUANIA', 'Lietuva', 'LT', 'LTU'],
    ['LIECHTENSTEIN', 'Liechtenstein', 'LI', 'LIE'],
    ['MADAGASCAR', 'Madagasikara', 'MG', 'MDG'],
    ['MARTINIQUE', 'Martinique', 'MQ', 'MTQ'],
    ['MARSHALL ISLANDS', 'Marshall Islands', 'MH', 'MHL'],
    ['MAYOTTE', 'Mayotte', 'YT', 'MYT'],
    ['MACAU', 'Macao', 'MO', 'MAC'],
    ['REPUBLIC OF MACEDONIA', 'Македонија', 'MK', 'MKD'],
    ['MALAWI', 'Malawi', 'MW', 'MWI'],
    ['MALAYSIA', 'Malaysia', 'MY', 'MYS'],
    ['MALI', 'Mali', 'ML', 'MLI'],
    ['ISLE OF MAN', 'Isle of Man', 'IM', 'IMN'],
    ['MEXICO', 'México', 'MX', 'MEX'],
    ['MONACO', 'Monaco', 'MC', 'MCO'],
    ['MOROCCO', 'المغرب', 'MA', 'MAR'],
    ['MAURITIUS', 'Mauritius', 'MU', 'MUS'],
    ['MAURITANIA', 'موريتانيا', 'MR', 'MRT'],
    ['MOZAMBIQUE', 'Moçambique', 'MZ', 'MOZ'],
    ['MONTENEGRO', 'Црна Гора', 'ME', 'MNE'],
    ['MONTSERRAT', 'Montserrat', 'MS', 'MSR'],
    ['MOLDOVA, REPUBLIC OF', 'Moldova', 'MD', 'MDA'],
    ['MALDIVES', 'ގުޖޭއްރާ ޔާއްރިހޫމްޖ', 'MV', 'MDV'],
    ['MALTA', 'Malta', 'MT', 'MLT'],
    ['MONGOLIA', 'Монгол Улс', 'MN', 'MNG'],
    ['UNITED STATES', 'United States', 'US', 'USA'],
    ['UNITED STATES MINOR OUTLYING ISLANDS', 'United States minor outlying islands', 'UM', 'UMI'],
    ['VIRGIN ISLANDS, U.S.', 'Virgin Islands, U.S.', 'VI', 'VIR'],
    ['MYANMAR', 'Myanmar(Burma)', 'MM', 'MMR'],
    ['MICRONESIA', 'Micronesia', 'FM', 'FSM'],
    ['VANUATU', 'Vanuatu', 'VU', 'VUT'],
    ['BAHRAIN', 'البحرين', 'BH', 'BHR'],
    ['BARBADOS', 'Barbados', 'BB', 'BRB'],
    ['VATICAN CITY STATE', 'Città del Vaticano', 'VA', 'VAT'],
    ['BAHAMAS', 'Bahamas', 'BS', 'BHS'],
    ['BANGLADESH', 'বাংলাদেশ', 'BD', 'BGD'],
    ['BERMUDA', 'Bermuda', 'BM', 'BMU'],
    ['BENIN', 'Bénin', 'BJ', 'BEN'],
    ['VENEZUELA', 'Venezuela', 'VE', 'VEN'],
    ['VIET NAM', 'Việt Nam', 'VN', 'VNM'],
    ['BELGIUM', 'België', 'BE', 'BEL'],
    ['BELARUS', 'Белару́сь', 'BY', 'BLR'],
    ['BELIZE', 'Belize', 'BZ', 'BLZ'],
    ['BOSNIA HERCEGOVINA', 'Bosna i Hercegovina', 'BA', 'BIH'],
    ['BOTSWANA', 'Botswana', 'BW', 'BWA'],
    ['BOLIVIA', 'Bolivia', 'BO', 'BOL'],
    ['BURUNDI', 'Uburundi', 'BI', 'BDI'],
    ['BURKINA FASO', 'Burkina Faso', 'BF', 'BFA'],
    ['BOUVET ISLAND', 'Bouvet Island', 'BV', 'BVT'],
    ['BHUTAN', 'འབྲུག་ཡུལ', 'BT', 'BTN'],
    ['NORTHERN MARIANA ISLANDS', 'Northern Mariana Islands', 'MP', 'MNP'],
    ['BULGARIA', 'България', 'BG', 'BGR'],
    ['BRAZIL', 'Brasil', 'BR', 'BRA'],
    ['BRUNEI DARUSSALAM', 'Brunei Darussalam', 'BN', 'BRN'],
    ['SAMOA', 'Samoa', 'WS', 'WSM'],
    ['SAUDI ARABIA', 'المملكة العربية السعودية', 'SA', 'SAU'],
    ['SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'South Georgia and the South Sandwich Islands', 'GS', 'SGS'],
    ['SAN MARINO', 'San Marino', 'SM', 'SMR'],
    ['SAO TOME AND PRINCIPE', 'São Tomé and Príncipe', 'ST', 'STP'],
    ['ST. PIERRE AND MIQUELON', 'Saint Pierre and Miquelon', 'PM', 'SPM'],
    ['WESTERN SAHARA', 'الصحراء الغربية', 'EH', 'ESH'],
    ['SENEGAL', 'Sénégal', 'SN', 'SEN'],
    ['SERBIA', 'Србија', 'RS', 'SRB'],
    ['SEYCHELLES', 'Seychelles', 'SC', 'SYC'],
    ['SAINT LUCIA', 'Saint Lucia', 'LC', 'LCA'],
    ['SAINT VINCENT AND THE GRENADINES', 'Saint Vincent and the Grenadines', 'VC', 'VCT'],
    ['SAINT KITTS AND NEVIS', 'Saint Kitts and Nevis', 'KN', 'KNA'],
    ['ST. HELENA', 'Saint Helena', 'SH', 'SHN'],
    ['SOMALIA', 'Soomaaliya', 'SO', 'SOM'],
    ['SOLOMON ISLANDS', 'Solomon Islands', 'SB', 'SLB'],
    ['SUDAN', 'السودان', 'SD', 'SDN'],
    ['SURINAME', 'Suriname', 'SR', 'SUR'],
    ['SRI LANKA', 'Sri Lanka', 'LK', 'LKA'],
    ['SVALBARD AND JAN MAYEN ISLANDS', 'Svalbard and Jan Mayen', 'SJ', 'SJM'],
    ['SWAZILAND', 'Swaziland', 'SZ', 'SWZ'],
    ['SWEDEN', 'Sverige', 'SE', 'SWE'],
    ['SWITZERLAND', 'Schweiz', 'CH', 'CHE'],
    ['SPAIN', 'España', 'ES', 'ESP'],
    ['SLOVAKIA', 'Slovensko', 'SK', 'SVK'],
    ['SLOVENIA', 'Slovenija', 'SI', 'SVN'],
    ['SYRIAN ARAB REPUBLIC', 'سوريا', 'SY', 'SYR'],
    ['SIERRA LEONE', 'Sierra Leone', 'SL', 'SLE'],
    ['SINGAPORE', 'Singapura', 'SG', 'SGP'],
    ['UNITED ARAB EMIRATES', 'الإمارات العربيّة المتّحدة', 'AE', 'ARE'],
    ['ARUBA', 'Aruba', 'AW', 'ABW'],
    ['ARMENIA', 'Հայաստան', 'AM', 'ARM'],
    ['ARGENTINA', 'Argentina', 'AR', 'ARG'],
    ['AMERICAN SAMOA', 'American Samoa', 'AS', 'ASM'],
    ['ICELAND', 'Ísland', 'IS', 'ISL'],
    ['HAITI', 'Haïti', 'HT', 'HTI'],
    ['IRELAND', 'Ireland', 'IE', 'IRL'],
    ['AZERBAIJAN', 'Azərbaycan', 'AZ', 'AZE'],
    ['AFGHANISTAN', 'افغانستان', 'AF', 'AFG'],
    ['ANDORRA', 'Andorra', 'AD', 'AND'],
    ['ALBANIA', 'Shqipëria', 'AL', 'ALB'],
    ['ALGERIA', 'الجزائر', 'DZ', 'DZA'],
    ['ANGOLA', 'Angola', 'AO', 'AGO'],
    ['ANTIGUA AND BARBUDA', 'Antigua and Barbuda', 'AG', 'ATG'],
    ['ANGUILLA', 'Anguilla', 'AI', 'AIA'],
    ['ERITREA', 'Ertra', 'ER', 'ERI'],
    ['ESTONIA', 'Eesti', 'EE', 'EST'],
    ['ECUADOR', 'Ecuador', 'EC', 'ECU'],
    ['ETHIOPIA', "Ityop'iya", 'ET', 'ETH'],
    ['EL SALVADOR', 'El Salvador', 'SV', 'SLV'],
    ['UNITED KINGDOM', 'United Kingdom', 'GB', 'GBR'],
    ['VIRGIN ISLANDS, BRITISH', 'Virgin Islands, British', 'VG', 'VGB'],
    ['BRITISH INDIAN OCEAN TERRITORY', 'British Indian Ocean Territory', 'IO', 'IOT'],
    ['YEMEN, REPUBLIC OF', 'اليمن', 'YE', 'YEM'],
    ['OMAN', 'عمان', 'OM', 'OMN'],
    ['AUSTRALIA', 'Australia', 'AU', 'AUS'],
    ['AUSTRIA', 'Österreich', 'AT', 'AUT'],
    ['HONDURAS', 'Honduras', 'HN', 'HND'],
    ['ALAND ISLANDS', 'Aland Islands', 'AX', 'ALA'],
    ['WALLIS AND FUTUNA ISLANDS', 'Wallis and Futuna', 'WF', 'WLF'],
    ['JORDAN', 'الاردن', 'JO', 'JOR'],
    ['UGANDA', 'Uganda', 'UG', 'UGA'],
    ['URUGUAY', 'Uruguay', 'UY', 'URY'],
    ['UZBEKISTAN', "O'zbekiston", 'UZ', 'UZB'],
    ['UKRAINE', 'Україна', 'UA', 'UKR'],
    ['IRAQ', 'العراق', 'IQ', 'IRQ'],
    ['IRAN', 'ایران', 'IR', 'IRN'],
    ['ISRAEL', 'ישראל', 'IL', 'ISR'],
    ['EGYPT', 'مصر', 'EG', 'EGY'],
    ['ITALY', 'Italia', 'IT', 'ITA'],
    ['INDIA', 'India', 'IN', 'IND'],
    ['INDONESIA', 'Indonesia', 'ID', 'IDN'],
    ['JAPAN', '日本', 'JP', 'JPN'],
    ['JAMAICA', 'Jamaica', 'JM', 'JAM'],
    ['ZAMBIA', 'Zambia', 'ZM', 'ZMB'],
    ['JERSEY', 'Jersey', 'JE', 'JEY'],
    ['EQUATORIAL GUINEA', 'Guinea Ecuatorial', 'GQ', 'GNQ'],
    ['GEORGIA', 'საქართველო', 'GE', 'GEO'],
    ['CENTRAL AFRICAN REPUBLIC', 'République Centrafricaine', 'CF', 'CAF'],
    ['TAIWAN, PROVINCE OF CHINA', '台灣', 'TW', 'TWN'],
    ['CHINA', '中国', 'CN', 'CHN'],
    ['DJIBOUTI', 'Djibouti', 'DJ', 'DJI'],
    ['GIBRALTAR', 'Gibraltar', 'GI', 'GIB'],
    ['ZIMBABWE', 'Zimbabwe', 'ZW', 'ZWE'],
    ['CHAD', 'Tchad', 'TD', 'TCD'],
    ['CZECH REPUBLIC', 'Česko', 'CZ', 'CZE'],
    ['CHILE', 'Chile', 'CL', 'CHL'],
    ['CAMEROON', 'Cameroun', 'CM', 'CMR'],
    ['CAPE VERDE', 'Cabo Verde', 'CV', 'CPV'],
    ['KAZAKHSTAN', 'Қазақстан', 'KZ', 'KAZ'],
    ['QATAR', 'قطر', 'QA', 'QAT'],
    ['CAMBODIA', 'Kampuchea', 'KH', 'KHM'],
    ['CANADA', 'Canada', 'CA', 'CAN'],
    ['KENYA', 'Kenya', 'KE', 'KEN'],
    ['CAYMAN ISLANDS', 'Cayman Islands', 'KY', 'CYM'],
    ['COMOROS', 'Comores', 'KM', 'COM'],
    ['COSTA RICA', 'Costa Rica', 'CR', 'CRI'],
    ['COCOS ISLANDS', 'Cocos Islands', 'CC', 'CCK'],
    ["COTE D'IVOIRE", "Côte d'Ivoire", 'CI', 'CIV'],
    ['COLOMBIA', 'Colombia', 'CO', 'COL'],
    ['CONGO', 'Congo', 'CG', 'COG'],
    ['DEMOCRATIC REPUBLIC OF THE CONGO', 'Congo, Democratic Republic of the', 'CD', 'COD'],
    ['CUBA', 'Cuba', 'CU', 'CUB'],
    ['KUWAIT', 'الكويت', 'KW', 'KWT'],
    ['COOK ISLANDS', 'Cook Islands', 'CK', 'COK'],
    ['CROATIA', 'Hrvatska', 'HR', 'HRV'],
    ['CHRISTMAS ISLAND', 'Christmas Island', 'CX', 'CXR'],
    ['KYRGYZSTAN', 'Кыргызстан', 'KG', 'KGZ'],
    ['KIRIBATI', 'Kiribati', 'KI', 'KIR'],
    ['CYPRUS', 'Κυπρος', 'CY', 'CYP'],
    ['THAILAND', 'ราชอาณาจักรไทย', 'TH', 'THA'],
    ['TAJIKISTAN', 'Тоҷикистон', 'TJ', 'TJK'],
    ['TANZANIA, UNITED REPUBLIC OF', 'Tanzania', 'TZ', 'TZA'],
    ['TURKS AND CAICOS ISLANDS', 'Turks and Caicos Islands', 'TC', 'TCA'],
    ['TURKEY', 'Türkiye', 'TR', 'TUR'],
    ['TOGO', 'Togo', 'TG', 'TGO'],
    ['TOKELAU', 'Tokelau', 'TK', 'TKL'],
    ['TONGA', 'Tonga', 'TO', 'TON'],
    ['TURKMENISTAN', 'Türkmenistan', 'TM', 'TKM'],
    ['TUVALU', 'Tuvalu', 'TV', 'TUV'],
    ['TUNISIA', 'تونس', 'TN', 'TUN'],
    ['TRINIDAD AND TOBAGO', 'Trinidad and Tobago', 'TT', 'TTO'],
    ['PANAMA', 'Panamá', 'PA', 'PAN'],
    ['PARAGUAY', 'Paraguay', 'PY', 'PRY'],
    ['PAKISTAN', 'پاکستان', 'PK', 'PAK'],
    ['PAPUA NEW GUINEA', 'Papua New Guinea', 'PG', 'PNG'],
    ['PALAU', 'Belau', 'PW', 'PLW'],
    ['PALESTINE', 'Palestinian Territories', 'PS', 'PSE'],
    ['FAROE ISLANDS', 'Faroe Islands', 'FO', 'FRO'],
    ['PERU', 'Perú', 'PE', 'PER'],
    ['PORTUGAL', 'Portugal', 'PT', 'PRT'],
    ['FALKLAND ISLANDS', 'Falkland Islands', 'FK', 'FLK'],
    ['POLAND', 'Polska', 'PL', 'POL'],
    ['PUERTO RICO', 'Puerto Rico', 'PR', 'PRI'],
    ['FRANCE', 'France', 'FR', 'FRA'],
    ['FRENCH GUIANA', 'French Guiana', 'GF', 'GUF'],
    ['FRENCH SOUTHERN TERRITORIES', 'French Southern Territories', 'TF', 'ATF'],
    ['FRENCH POLYNESIA', 'French Polynesia', 'PF', 'PYF'],
    ['FIJI', 'Fiji', 'FJ', 'FJI'],
    ['FINLAND', 'Suomi', 'FI', 'FIN'],
    ['PHILIPPINES', 'Pilipinas', 'PH', 'PHL'],
    ['PITCAIRN', 'Pitcairn', 'PN', 'PCN'],
    ['HEARD AND MC DONALD ISLANDS', 'Heard Island and McDonald Islands', 'HM', 'HMD'],
    ['HUNGARY', 'Magyarország', 'HU', 'HUN'],
    ['HONG KONG', 'Hong Kong', 'HK', 'HKG']
]


def convert_country_to_code(target,type=2):
    target = target.casefold()
    result = ["Unknown","Unknown","__","___"]
    for i in country_code:
        if i[INDX_COUNTRY_NAME_EN].casefold() == target \
            or i[INDX_COUNTRY_NAME_NA].casefold() == target:
            result = i
            break

    if type == 2:
        return result[INDX_COUNTRY_CODE2]
    else:
        return result[INDX_COUNTRY_CODE3]


def convert_code_to_country(target,type="EN"):
    result = ["Unknown","Unknown","en","eng"]
    for i in country_code:
        if i[INDX_COUNTRY_CODE2] == target \
            or i[INDX_COUNTRY_CODE3] == target:
            result = i
            break

    if type == "EN":
        return result[INDX_COUNTRY_NAME_EN]
    else:
        return result[INDX_COUNTRY_NAME_NA]
    