# Based on ISO 639-1

INDX_LANG_NAME_EN = 0
INDX_LANG_NAME_NA = 1
INDX_LANG_CODE2 = 2
INDX_LANG_CODE3 = 3

lang_code = [
    [ 'Abkhazian', 'аҧсуа бызшәа', 'ab', 'abk'],
    [ 'Afar', 'Afaraf', 'aa', 'aar'],
    [ 'Afrikaans', 'Afrikaans', 'af', 'afr'],
    [ 'Akan', 'Akan', 'ak', 'aka'],
    [ 'Albanian', 'Shqip', 'sq', 'sqi'],
    [ 'Amharic', 'አማርኛ', 'am', 'amh'],
    [ 'Arabic', 'العربية', 'ar', 'ara'],
    [ 'Aragonese', 'aragonés', 'an', 'arg'],
    [ 'Armenian', 'Հայերեն', 'hy', 'hye'],
    [ 'Assamese', 'অসমীয়া', 'as', 'asm'],
    [ 'Avaric', 'авар мацӀ', 'av', 'ava'],
    [ 'Avestan', 'avesta', 'ae', 'ave'],
    [ 'Aymara', 'aymar aru', 'ay', 'aym'],
    [ 'Azerbaijani', 'azərbaycan dili', 'az', 'aze'],
    [ 'Bambara', 'bamanankan', 'bm', 'bam'],
    [ 'Bashkir', 'башҡорт теле', 'ba', 'bak'],
    [ 'Basque', 'euskara', 'eu', 'eus'],
    [ 'Belarusian', 'беларуская мова', 'be', 'bel'],
    [ 'Bengali', 'বাংলা', 'bn', 'ben'],
    [ 'Bislama', 'Bislama', 'bi', 'bis'],
    [ 'Bosnian', 'bosanski jezik', 'bs', 'bos'],
    [ 'Breton', 'brezhoneg', 'br', 'bre'],
    [ 'Bulgarian', 'български език', 'bg', 'bul'],
    [ 'Burmese', 'ဗမာစာ', 'my', 'mya'],
    [ 'Catalan', 'català', 'ca', 'cat'],
    [ 'Chamorro', 'Chamoru', 'ch', 'cha'],
    [ 'Chechen', 'нохчийн мотт', 'ce', 'che'],
    [ 'Chichewa', 'chiCheŵa', 'ny', 'nya'],
    [ 'Chinese', '中文', 'zh', 'zho'],
    [ 'Church Slavonic', 'ѩзыкъ словѣньскъ', 'cu', 'chu'],
    [ 'Chuvash', 'чӑваш чӗлхи', 'cv', 'chv'],
    [ 'Cornish', 'Kernewek', 'kw', 'cor'],
    [ 'Corsican', 'corsu', 'co', 'cos'],
    [ 'Cree', 'ᓀᐦᐃᔭᐍᐏᐣ', 'cr', 'cre'],
    [ 'Croatian', 'hrvatski jezik', 'hr', 'hrv'],
    [ 'Czech', 'čeština', 'cs', 'ces'],
    [ 'Danish', 'dansk', 'da', 'dan'],
    [ 'Divehi', 'ދިވެހި', 'dv', 'div'],
    [ 'Dutch', 'Nederlands', 'nl', 'nld'],
    [ 'Dzongkha', 'རྫོང་ཁ', 'dz', 'dzo'],
    [ 'English', 'English', 'en', 'eng'],
    [ 'Estonian', 'eesti', 'et', 'est'],
    [ 'Faroese', 'føroyskt', 'fo', 'fao'],
    [ 'Fijian', 'vosa Vakaviti', 'fj', 'fij'],
    [ 'Finnish', 'suomi', 'fi', 'fin'],
    [ 'French', 'français', 'fr', 'fra'],
    [ 'Western Frisian', 'Frysk', 'fy', 'fry'],
    [ 'Fulah', 'Fulfulde', 'ff', 'ful'],
    [ 'Gaelic', 'Gàidhlig', 'gd', 'gla'],
    [ 'Galician', 'Galego', 'gl', 'glg'],
    [ 'Ganda', 'Luganda', 'lg', 'lug'],
    [ 'Georgian', 'ქართული', 'ka', 'kat'],
    [ 'German', 'Deutsch', 'de', 'deu'],
    [ 'Greek', 'ελληνικά', 'el', 'ell'],
    [ 'Kalaallisut', 'kalaallisut', 'kl', 'kal'],
    [ 'Guarani', "Avañe'ẽ", 'gn', 'grn'],
    [ 'Gujarati', 'ગુજરાતી', 'gu', 'guj'],
    [ 'Haitian', 'Kreyòl ayisyen', 'ht', 'hat'],
    [ 'Hausa', 'هَوُسَ', 'ha', 'hau'],
    [ 'Hebrew', 'עברית', 'he', 'heb'],
    [ 'Herero', 'Otjiherero', 'hz', 'her'],
    [ 'Hindi', 'हिन्दी', 'hi', 'hin'],
    [ 'Hiri Motu', 'Hiri Motu', 'ho', 'hmo'],
    [ 'Hungarian', 'magyar', 'hu', 'hun'],
    [ 'Icelandic', 'Íslenska', 'is', 'isl'],
    [ 'Igbo', 'Asụsụ Igbo', 'ig', 'ibo'],
    [ 'Indonesian', 'Bahasa Indonesia', 'id', 'ind'],
    [ 'Inuktitut', 'ᐃᓄᒃᑎᑐᑦ', 'iu', 'iku'],
    [ 'Inupiaq', 'Iñupiaq', 'ik', 'ipk'],
    [ 'Irish', 'Gaeilge', 'ga', 'gle'],
    [ 'Italian', 'Italiano', 'it', 'ita'],
    [ 'Japanese', '日本語', 'ja', 'jpn'],
    [ 'Javanese', 'ꦧꦱꦗꦮ', 'jv', 'jav'],
    [ 'Kannada', 'ಕನ್ನಡ', 'kn', 'kan'],
    [ 'Kanuri', 'Kanuri', 'kr', 'kau'],
    [ 'Kashmiri', 'कश्मीरी', 'ks', 'kas'],
    [ 'Kazakh', 'қазақ тілі', 'kk', 'kaz'],
    [ 'Central Khmer', 'ខ្មែរ', 'km', 'khm'],
    [ 'Kikuyu', 'Gĩkũyũ', 'ki', 'kik'],
    [ 'Kinyarwanda', 'Ikinyarwanda', 'rw', 'kin'],
    [ 'Kirghiz', 'Кыргызча', 'ky', 'kir'],
    [ 'Komi', 'коми кыв', 'kv', 'kom'],
    [ 'Kongo', 'Kikongo', 'kg', 'kon'],
    [ 'Korean', '한국어', 'ko', 'kor'],
    [ 'Kuanyama', 'Kuanyama', 'kj', 'kua'],
    [ 'Kurdish', 'Kurdî', 'ku', 'kur'],
    [ 'Lao', 'ພາສາລາວ', 'lo', 'lao'],
    [ 'Latin', 'latine', 'la', 'lat'],
    [ 'Latvian', 'latviešu valoda', 'lv', 'lav'],
    [ 'Limburgan', 'Limburgs', 'li', 'lim'],
    [ 'Lingala', 'Lingála', 'ln', 'lin'],
    [ 'Lithuanian', 'lietuvių kalba', 'lt', 'lit'],
    [ 'Luba-Katanga', 'Kiluba', 'lu', 'lub'],
    [ 'Luxembourgish', 'Lëtzebuergesch', 'lb', 'ltz'],
    [ 'Macedonian', 'македонски јазик', 'mk', 'mkd'],
    [ 'Malagasy', 'fiteny malagasy', 'mg', 'mlg'],
    [ 'Malay', 'Bahasa Melayu', 'ms', 'msa'],
    [ 'Malayalam', 'മലയാളം', 'ml', 'mal'],
    [ 'Maltese', 'Malti', 'mt', 'mlt'],
    [ 'Manx', 'Gaelg', 'gv', 'glv'],
    [ 'Maori', 'te reo Māori', 'mi', 'mri'],
    [ 'Marathi', 'मराठी', 'mr', 'mar'],
    [ 'Marshallese', 'Kajin M̧ajeļ', 'mh', 'mah'],
    [ 'Mongolian', 'Монгол хэл', 'mn', 'mon'],
    [ 'Nauru', 'Dorerin Naoero', 'na', 'nau'],
    [ 'Navajo', 'Diné bizaad', 'nv', 'nav'],
    [ 'North Ndebele', 'isiNdebele', 'nd', 'nde'],
    [ 'South Ndebele', 'isiNdebele', 'nr', 'nbl'],
    [ 'Ndonga', 'Owambo', 'ng', 'ndo'],
    [ 'Nepali', 'नेपाली', 'ne', 'nep'],
    [ 'Norwegian', 'Norsk', 'no', 'nor'],
    [ 'Norwegian Bokmål', 'Norsk Bokmål', 'nb', 'nob'],
    [ 'Norwegian Nynorsk', 'Norsk Nynorsk', 'nn', 'nno'],
    [ 'Sichuan Yi', 'ꆈꌠ꒿ Nuosuhxop', 'ii', 'iii'],
    [ 'Occitan', 'occitan', 'oc', 'oci'],
    [ 'Ojibwa', 'ᐊᓂᔑᓈᐯᒧᐎᓐ', 'oj', 'oji'],
    [ 'Oriya', 'ଓଡ଼ିଆ', 'or', 'ori'],
    [ 'Oromo', 'Afaan Oromoo', 'om', 'orm'],
    [ 'Ossetian', 'ирон æвзаг', 'os', 'oss'],
    [ 'Pali', 'पाऴि', 'pi', 'pli'],
    [ 'Pashto', 'پښتو', 'ps', 'pus'],
    [ 'Persian', 'فارسی', 'fa', 'fas'],
    [ 'Polish', 'język polski', 'pl', 'pol'],
    [ 'Portuguese', 'Português', 'pt', 'por'],
    [ 'Punjabi', 'ਪੰਜਾਬੀ', 'pa', 'pan'],
    [ 'Quechua', 'Runa Simi', 'qu', 'que'],
    [ 'Romanian', 'Română', 'ro', 'ron'],
    [ 'Romansh', 'Rumantsch Grischun', 'rm', 'roh'],
    [ 'Rundi', 'Ikirundi', 'rn', 'run'],
    [ 'Russian', 'русский', 'ru', 'rus'],
    [ 'Northern Sami', 'Davvisámegiella', 'se', 'sme'],
    [ 'Samoan', "gagana fa'a Samoa", 'sm', 'smo'],
    [ 'Sango', 'yângâ tî sängö', 'sg', 'sag'],
    [ 'Sanskrit', 'संस्कृतम्', 'sa', 'san'],
    [ 'Sardinian', 'sardu', 'sc', 'srd'],
    [ 'Serbian', 'српски језик', 'sr', 'srp'],
    [ 'Shona', 'chiShona', 'sn', 'sna'],
    [ 'Sindhi', 'सिन्धी', 'sd', 'snd'],
    [ 'Sinhala', 'සිංහල', 'si', 'sin'],
    [ 'Slovak', 'Slovenčina', 'sk', 'slk'],
    [ 'Slovenian', 'Slovenski Jezik', 'sl', 'slv'],
    [ 'Somali', 'Soomaaliga', 'so', 'som'],
    [ 'Southern Sotho', 'Sesotho', 'st', 'sot'],
    [ 'Spanish', 'Español', 'es', 'spa'],
    [ 'Sundanese', 'Basa Sunda', 'su', 'sun'],
    [ 'Swahili', 'Kiswahili', 'sw', 'swa'],
    [ 'Swati', 'SiSwati', 'ss', 'ssw'],
    [ 'Swedish', 'Svenska', 'sv', 'swe'],
    [ 'Tagalog', 'Wikang Tagalog', 'tl', 'tgl'],
    [ 'Tahitian', 'Reo Tahiti', 'ty', 'tah'],
    [ 'Tajik', 'тоҷикӣ', 'tg', 'tgk'],
    [ 'Tamil', 'தமிழ்', 'ta', 'tam'],
    [ 'Tatar', 'татар теле', 'tt', 'tat'],
    [ 'Telugu', 'తెలుగు', 'te', 'tel'],
    [ 'Thai', 'ไทย', 'th', 'tha'],
    [ 'Tibetan', 'བོད་ཡིག', 'bo', 'bod'],
    [ 'Tigrinya', 'ትግርኛ', 'ti', 'tir'],
    [ 'Tonga', 'Faka Tonga', 'to', 'ton'],
    [ 'Tsonga', 'Xitsonga', 'ts', 'tso'],
    [ 'Tswana', 'Setswana', 'tn', 'tsn'],
    [ 'Turkish', 'Türkçe', 'tr', 'tur'],
    [ 'Turkmen', 'Türkmen', 'tk', 'tuk'],
    [ 'Twi', 'Twi', 'tw', 'twi'],
    [ 'Uighur', 'Uyghurche', 'ug', 'uig'],
    [ 'Ukrainian', 'Українська', 'uk', 'ukr'],
    [ 'Urdu', 'اردو', 'ur', 'urd'],
    [ 'Uzbek', 'Ўзбек', 'uz', 'uzb'],
    [ 'Venda', 'Tshivenḓa', 've', 'ven'],
    [ 'Vietnamese', 'Tiếng Việt', 'vi', 'vie'],
    [ 'Walloon', 'Walon', 'wa', 'wln'],
    [ 'Welsh', 'Cymraeg', 'cy', 'cym'],
    [ 'Wolof', 'Wollof', 'wo', 'wol'],
    [ 'Xhosa', 'isiXhosa', 'xh', 'xho'],
    [ 'Yiddish', 'ייִדיש', 'yi', 'yid'],
    [ 'Yoruba', 'Yorùbá', 'yo', 'yor'],
    [ 'Zhuang', 'Saw cuengh', 'za', 'zha'],
    [ 'Zulu', 'isiZulu', 'zu', 'zul']
]


def convert_lang_to_code(target,type=2):
    target = target.casefold()
    result = ["Unknown","Unknown","en","eng"]
    for i in lang_code:
        if i[INDX_LANG_NAME_EN].casefold() == target \
            or i[INDX_LANG_NAME_NA].casefold() == target:
            result = i
            break

    if type == 2:
        return result[INDX_LANG_CODE2]
    else:
        return result[INDX_LANG_CODE3]


def convert_code_to_lang(target,type="EN"):
    result = ["Unknown","Unknown","en","eng"]
    for i in lang_code:
        if i[INDX_LANG_CODE2] == target \
            or i[INDX_LANG_CODE3] == target:
            result = i
            break

    if type == "EN":
        return result[INDX_LANG_NAME_EN]
    else:
        return result[INDX_LANG_NAME_NA]
    